 
on:
  push:
    branches: [master]

name: Publish cdk

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: cdk synth
      uses: youyo/aws-cdk-github-actions@v2.0.2
      with:
        cdk_subcommand: 'synth'

    - name: cdk deploy
      uses: youyo/aws-cdk-github-actions@v2.0.2
      with:
        cdk_subcommand: 'deploy'
        cdk_stack: '--all'
        cdk_args: '--require-approval never'
        actions_comment: false
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-2'

